export const Bar = () => null
export const BarChart = () => null
export const XAxis = () => null
export const YAxis = () => null
export const Tooltip = () => null
export const ResponsiveContainer = () => null
export const Radar = () => null
export const RadarChart = () => null
export const PolarGrid = () => null
export const PolarAngleAxis = () => null
export const PolarRadiusAxis = () => null
